# Generated by Django 3.2.6 on 2021-08-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pageCount', models.IntegerField(default=0)),
                ('thumbnailUrl', models.CharField(max_length=200, null=True)),
                ('shortDescription', models.CharField(max_length=100, null=True)),
                ('longDescription', models.TextField(max_length=500, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('isbn', models.IntegerField(default=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500)),
            ],
        ),
    ]
