# Generated by Django 3.2.6 on 2021-08-15 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_review_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book_id',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='book_app.book'),
        ),
    ]
